# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
PATH = 'export PATH="$PATH:{{ dir }}"'

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fzf]
inline = "source <(fzf --zsh)"

[plugins.zoxide]
inline = 'eval "$(zoxide init zsh)"'

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.terraform-completion]
inline = '''
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform
'''

[plugins.gcloud-sdk]
inline = '''
brew_prefix="$(brew --prefix)"
if [ -f "$brew_prefix/share/google-cloud-sdk/path.zsh.inc" ]; then
  source "$brew_prefix/share/google-cloud-sdk/path.zsh.inc"
  source "$brew_prefix/share/google-cloud-sdk/completion.zsh.inc"
fi
'''

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
apply = ["defer"]


[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]
