# reference: https://github.com/starship/starship/discussions/1107#discussioncomment-7554693

format = """
[ ](bg:color_bg1)\
$os\
$directory\
$git_branch\
$git_status\
[ ](fg:color_bg1)
$character
"""

right_format = """
[](fg:color_bg1)\
$status\
$python\
$cmd_duration\
$custom
"""

command_timeout = 1000

palette = 'p10k_dark'

[palettes.p10k_dark]
color_bg1 = '#222222'

[cmd_duration]
format = "[](fg:#7a7a7a bg:color_bg1)[ $duration ]($style)"
style = "fg:#9b9b9b bg:color_bg1"

[os]
disabled = false
style = "fg:#ffffff bg:color_bg1"

[os.symbols]
Ubuntu = "󰕈"
Macos = "󰀵"

[custom]
[custom.direnv]
format = "[](fg:#7a7a7a bg:color_bg1)[ $symbol ]($style)"
style = "fg:#7a7a7a bg:color_bg1"
symbol = "[▼](fg:white bg:color_bg1)"
when = "test \"$DIRENV_WATCHES\" != \"\""

[directory]
style = "fg:#00afff bg:color_bg1"
format = "[ ](fg:#7a7a7a bg:color_bg1)[  $path ]($style)"
truncate_to_repo = true
truncation_length = 5
fish_style_pwd_dir_length = 1

[git_branch]
format = "[ on](fg:#7a7a7a bg:color_bg1)[ 󰊤 󰘬]($style)[ $branch(:$remote_branch) ]($style)"
style = "fg:#00dd00 bg:color_bg1"

[git_metrics]
added_style = "fg:#c4b51e bg:color_bg1"
deleted_style = "fg:bright-red bg:235"
disabled = false
format = "([+$added]($added_style))[]($added_style)"

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count⇣$behind_count"
format = "[$all_status$ahead_behind ]($style)"
modified = "[!$count ](fg:#c4b51e bg:color_bg1)"
style = "fg:#c4b51e bg:color_bg1"
untracked = "[?$count ](fg:#00afff bg:color_bg1)"

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[status]
disabled = false
format = "[ $signal_name $symbol ]($style)"
map_symbol = true
style = "bg:color_bg1"
success_symbol = "[✔](fg:green bg:color_bg1)"
symbol = "[✘](fg:#d60202 bg:#444444)"


[python]
pyenv_version_name = true
symbol = ''
format = ' [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
